### ISSUE TITLE
Find graphics for chess pieces 

### ISSUE THREAD

**Issue by sungyeonu** [sungyeonu/remote-chess-simulator#4]
Please vote by using emoticons on upper right corner like how i thumbed up this comment

**Comment by sungyeonu** [comment]
https://commons.wikimedia.org/wiki/Category:PNG_chess_pieces/Standard_transparent
![image](https://user-images.githubusercontent.com/47223114/72015601-0f049900-3230-11ea-9a3d-2a074df42dc7.png)

**Comment by sungyeonu** [comment]
https://icons8.com/icons/set/chess

These ones are pretty 
![image](https://user-images.githubusercontent.com/47223114/72015584-02804080-3230-11ea-9963-215629e791c7.png)

**Comment by sungyeonu** [comment]
https://en.wikipedia.org/wiki/Chess_symbols_in_Unicode

![image](https://user-images.githubusercontent.com/47223114/72015664-30fe1b80-3230-11ea-945a-0d52b248fffa.png)

**Comment by sungyeonu** [comment]
http://www.enpassant.dk/chess/fonteng.htm 

This one has several fonts

**Comment by aliyeysides** [comment]
> Please vote by using emoticons on upper right corner like how i thumbed up this comment

wow you upvoted your own comment wow

**Comment by sungyeonu** [comment]
https://www.flaticon.com/packs/chess-7

This one has two color schemes and look modern

![image](https://user-images.githubusercontent.com/47223114/72287873-d7259900-3615-11ea-8281-3edc3b7a0a8d.png)

**Comment by sungyeonu** [comment]
![image](https://user-images.githubusercontent.com/47223114/72288075-41d6d480-3616-11ea-8383-fcd02c281346.png)
https://www.flaticon.com/packs/chess-8

**Comment by darianshi** [comment]
> https://www.flaticon.com/packs/chess-7
> 
> This one has two color schemes and look modern
> 
> ![image](https://user-images.githubusercontent.com/47223114/72287873-d7259900-3615-11ea-8281-3edc3b7a0a8d.png)

bishop and queen look really similar
